# Generated by Django 3.2.5 on 2022-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=9)),
                ('department', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('degree_other', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=255)),
                ('no_of_mentees', models.CharField(max_length=255)),
                ('referral', models.CharField(max_length=255)),
                ('suggestions', models.TextField()),
                ('profiles', models.CharField(max_length=255)),
                ('pref1', models.CharField(max_length=255)),
                ('pref2', models.CharField(max_length=255)),
                ('core', models.CharField(max_length=100)),
                ('aerospace', models.CharField(max_length=100)),
                ('chemical', models.CharField(max_length=100)),
                ('bsbe', models.CharField(max_length=100)),
                ('earthscience', models.CharField(max_length=100)),
                ('ep', models.CharField(max_length=100)),
                ('mems', models.CharField(max_length=100)),
                ('maths', models.CharField(max_length=100)),
                ('ieor', models.CharField(max_length=100)),
                ('civil', models.CharField(max_length=100)),
                ('chemistry', models.CharField(max_length=100)),
                ('electrical', models.CharField(max_length=100)),
                ('energy', models.CharField(max_length=100)),
                ('mechanical', models.CharField(max_length=100)),
                ('other_mentorship', models.CharField(max_length=100)),
            ],
        ),
    ]
