# Generated by Django 3.2.5 on 2022-06-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='other_department',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
